import Head from "next/head";
import {
  Center,
  Card,
  Input,
  Slider,
  Switch,
  Text,
  Stack,
  Group,
  Button,
  Space,
} from "@mantine/core";

export default function Home() {
  return (
    <>
      <Head>
        <title>Password Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center style={{ height: "100vh", width: "100vw" }}>
          <Card shadow="sm" padding="xl" radius="md" withBorder>
            <Text weight={700} align="center">
              Password Generator
            </Text>
            <Stack m="xl" spacing="xl">
              <Group>
                <Input size="lg" />
              </Group>
              <Text>Length:</Text>
              <Slider
                size="sm"
                min={8}
                max={30}
                marks={[
                  { value: 8, label: "8" },
                  { value: 18, label: "18" },
                  { value: 28, label: "28" },
                ]}
              />
              <Space />
              <Switch label="With numbers" />
              <Switch label="With special characters" />
              <Group position="center" pt="md">
                <Button>Select</Button>
                <Button>Cancel</Button>
              </Group>
            </Stack>
          </Card>
        </Center>
      </main>
    </>
  );
}
